services:
    shlink_nginx:
        container_name: shlink_nginx
        image: nginx:1.25-alpine
        ports:
            - "8000:80"
        volumes:
            - ./:/home/shlink/www
            - ./docs:/home/shlink/www/public/docs
            - ./data/infra/vhost.conf:/etc/nginx/conf.d/default.conf
        links:
            - shlink_php

    shlink_frankenphp:
      container_name: shlink_frankenphp
      user: 1000:1000
      build:
        context: .
        dockerfile: ./data/infra/frankenphp.Dockerfile
      ports:
        - "8008:8008"
      volumes:
        - ./:/home/shlink
        - ./data/infra/php.ini:/usr/local/etc/php/php.ini
        - ./data/infra/frankenphp_caddy_data:/data
        - ./data/infra/frankenphp_caddy_config:/config
      links:
        - shlink_db_mysql
        - shlink_db_postgres
        - shlink_db_maria
        - shlink_db_ms
        - shlink_redis
        - shlink_redis_acl
        - shlink_mercure
        - shlink_mercure_proxy
        - shlink_rabbitmq
        - shlink_matomo
      environment:
        FRANKENPHP_CONFIG: 'worker /home/shlink/bin/frankenphp-worker.php'
        SERVER_NAME: ':8008 https:8009'
      extra_hosts:
        - 'host.docker.internal:host-gateway'
      tty: true

    shlink_db_postgres:
        container_name: shlink_db_postgres
        user: 1000:1000
        image: postgres:16.3-alpine
        ports:
            - "5434:5432"
        volumes:
            - ./:/home/shlink/www
            - ./data/infra/database_pg:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_DB: shlink
            PGDATA: /var/lib/postgresql/data/pgdata
